version: "3.1"
services:
    www:
        build: .
        environment:
            XDEBUG_CONFIG: remote_host=host.docker.internal remote_port=9000 remote_enable=1
        ports: 
            - "8000:80"
        volumes:
            - ./www:/var/www/html/
            - ./config/php.ini:/usr/local/etc/php/php.ini
        links:
            - db:db
        networks:
            - default
    db:
        image: mysql:5.6
        ports: 
            - "3306:3306"
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_DATABASE: test_database
            MYSQL_USER:  ## YOUR USER NAME ##
            MYSQL_PASSWORD: ## YOUR PASSWORD ##
            MYSQL_ROOT_PASSWORD: ## YOUR ROOT PASSWORD ##
        volumes:
            - ./dump:/docker-entrypoint-initdb.d
            - ./conf:/etc/mysql/conf.d
            - persistent:/var/lib/mysql
        networks:
            - default

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links: 
            - db:db
        ports:
            - 8001:80
        environment:
            MYSQL_USER:  ## YOUR USER NAME ##
            MYSQL_PASSWORD: ## YOUR PASSWORD ##
            MYSQL_ROOT_PASSWORD: ## YOUR ROOT PASSWORD ##

## This might be used for persistence but it's optional.        
volumes:
    persistent:
